version: "3.3"

services:
  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    volumes:
      - "./public/:/app"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "80:80"
    depends_on:
      - symfony

  go:
    image: alpine
    volumes:
      - "./go:/app"
    working_dir: /app
    command: "./main"
