version: "3.3"

services:
  symfony:
    build: docker/symfony
    volumes:
      - .:/app
    command: "/usr/local/bin/symfony server:start --port 8080"
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - .env.local # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  mercure:
    # In production, you may want to use the managed version of Mercure, https://mercure.rocks
    image: dunglas/mercure
    command: caddy run -config /etc/caddy/Caddyfile.dev # Enable demo mode
    env_file:
      - .env.local # configure mercure
    ports:
      - 8082:80
      - 443:433
volumes:
  database-data:
